services:
  postgres:
    image: postgres:16
    container_name: postgres_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: idamantsl_db   
    ports:
      - "5433:5432"
    volumes:
      - idamantsl_postgres_data:/var/lib/postgresql/data

volumes:
  idamantsl_postgres_data: